[package]
name = "TodoTui"
version = "0.1.0"
edition = "2021"

[dependencies]
homedir = "0.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui = "0.29"
crossterm = "0.28"
